server:
  port: 8999
spring:
  kafka:
    producer:
      bootstrap-servers: "192.168.65.132:11001,192.168.65.132:11002,192.168.65.132:11003"
      batch-size: 16384
      retries: 0
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
