server:
  port: 2181
kafka:
  consumer:
    enable-auto-commit: true
    group-id: gridMonitorGroup
    auto-commit-interval: 1000
    auto-offset-reset: latest
    bootstrap-servers: "192.168.65.132:11001,192.168.65.132:11002,192.168.65.132:11003"
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    concurrency: 3