server:
  port: 9001
spring:
  application:
    name: USER-PROVIDER #不能使用下划线，否则服务不能使用
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
#      defaultZone: http://eureka-7001.com:7001/eureka,http://eureka-7002.com:7002/eureka #集群环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
