spring:
  rabbitmq:
    host: 192.168.65.134
    port: 5672
    username: myuser
    password: mypass
    listener:
      simple:
        concurrency: 5
        acknowledge-mode: manual
        max-concurrency: 10
        prefetch: 1
log:
  user:
    queue:
      name: local.log.user.queue
    exchange:
      name: local.log.user.exchange
    routing:
      key:
        name: local.log.user.routing.key
mail:
  queue:
    name: local.mail.queue
  exchange:
    name: local.mail.exchange
  routing:
    key:
      name: local.mail.routing.key
server:
  port: 8081
